# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d78291010e272eb356add23b0934086f833d37daf39b671e3fdc84239bb6b86ed295620707d150ecd16e1d47dc646d0140d219f83a0ac7ba9fc7fd6541d1c7

test:
  secret_key_base: 0b23b5506b58876c723e5c47eed60fc1f0c670a1b35100e89c88c6620388176c002947d4fff891292bb1a0e899afbc3d68965da427736feb6a4d49cdb1779f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
